### ISSUE TITLE
Cannot switch on Heating via Dzvents script

### ISSUE THREAD

**Issue by Krakinou** [JanJaapKo/DysonPureLink#42] opened 2021-10-19 22:31 UTC
Hi,

Domoticz Version : 2021.1 - Python Version: 3.7.3
Hardware : Raspi3B+
Plugin Version : latest master
Dyson : Dyson Pure PT4-EU-NEA5093A

I've some troubles to use this plugin to switch on the heat mode via DzVents script:
- switching on manually the Heat Mode from the control panel is working
- using `heatmode.switchSelector(10)` is shutting down the heating as expected
- using `heatmode.switchSelector('Off')` is not working and do nothing.
- using `heatmode.switchSelector(20)` is behaving as `heatmode.switchSelector(10)`, which is shutting down the device instead of setting it on.
- All other commands (oscillating, fan mode, night mode, etc.) seems to work perfectly well from Dzvents

Here is a sample of the script:
````
	execute = function(domoticz, timer)
	    local heatmode = domoticz.devices('Dyson Pure - Heat mode')

		--This do nothing
		heatmode.switchSelector(20)
		--This do nothing either
		heatmode.switchSelector('Heating')	
````

Here are the logs when trying to switch on via the script with `heatmode.switchSelector(20)` ( not working):
````
 2021-10-20 00:07:00.466 Dyson Pure: (Dyson Pure) DysonPureLink plugin: onCommand called for Unit 18: Parameter 'Set Level', Level: 10
2021-10-20 00:07:00.470 Dyson Pure: (Dyson Pure) MqttClient::Publish 455/PT4-EU-NEA5093A/command ({"msg": "STATE-SET", "mode-reason": "LAPP", "data": {"hmod": "OFF"}, "time": "2021-10-19T22:07:00Z"})
2021-10-20 00:07:00.471 Dyson Pure: (Dyson Pure) Sending 132 bytes of data
2021-10-20 00:07:00.471 Dyson Pure: (Dyson Pure) 30 81 01 00 1b 34 35 35 2f 50 54 34 2d 45 55 2d 4e 45 41 35 0�..455/PT4-EU-NEA5
2021-10-20 00:07:00.472 Dyson Pure: (Dyson Pure) 30 39 33 41 2f 63 6f 6d 6d 61 6e 64 7b 22 6d 73 67 22 3a 20 093A/command{"msg":.
2021-10-20 00:07:00.473 Dyson Pure: (Dyson Pure) 22 53 54 41 54 45 2d 53 45 54 22 2c 20 22 6d 6f 64 65 2d 72 "STATE-SET",."mode-r
2021-10-20 00:07:00.473 Dyson Pure: (Dyson Pure) 65 61 73 6f 6e 22 3a 20 22 4c 41 50 50 22 2c 20 22 64 61 74 eason":."LAPP",."dat
2021-10-20 00:07:00.474 Dyson Pure: (Dyson Pure) 61 22 3a 20 7b 22 68 6d 6f 64 22 3a 20 22 4f 46 46 22 7d 2c a":.{"hmod":."OFF"},
2021-10-20 00:07:00.474 Dyson Pure: (Dyson Pure) 20 22 74 69 6d 65 22 3a 20 22 32 30 32 31 2d 31 30 2d 31 39 ."time":."2021-10-19
2021-10-20 00:07:00.475 Dyson Pure: (Dyson Pure) 54 32 32 3a 30 37 3a 30 30 5a 22 7d .. .. .. .. .. .. .. .. T22:07:00Z"}
2021-10-20 00:07:00.876 Dyson Pure: (Dyson Pure) Received 535 bytes of data
2021-10-20 00:07:00.877 Dyson Pure: (Dyson Pure) 30 94 04 00 22 34 35 35 2f 50 54 34 2d 45 55 2d 4e 45 41 35 0Ԯ."455/PT4-EU-NEA5
2021-10-20 00:07:00.878 Dyson Pure: (Dyson Pure) 30 39 33 41 2f 73 74 61 74 75 73 2f 63 75 72 72 65 6e 74 7b 093A/status/current{
2021-10-20 00:07:00.878 Dyson Pure: (Dyson Pure) 22 6d 73 67 22 3a 22 53 54 41 54 45 2d 43 48 41 4e 47 45 22 "msg":"STATE-CHANGE"
2021-10-20 00:07:00.879 Dyson Pure: (Dyson Pure) 2c 22 74 69 6d 65 22 3a 22 32 30 32 31 2d 31 30 2d 31 39 54 ,"time":"2021-10-19T
2021-10-20 00:07:00.879 Dyson Pure: (Dyson Pure) 32 32 3a 30 37 3a 30 31 2e 30 30 30 5a 22 2c 22 6d 6f 64 65 22:07:01.000Z","mode
2021-10-20 00:07:00.880 Dyson Pure: (Dyson Pure) 2d 72 65 61 73 6f 6e 22 3a 22 4c 41 50 50 22 2c 22 73 74 61 -reason":"LAPP","sta
2021-10-20 00:07:00.881 Dyson Pure: (Dyson Pure) 74 65 2d 72 65 61 73 6f 6e 22 3a 22 4d 4f 44 45 22 2c 22 70 te-reason":"MODE","p
2021-10-20 00:07:00.881 Dyson Pure: (Dyson Pure) 72 6f 64 75 63 74 2d 73 74 61 74 65 22 3a 7b 22 66 6d 6f 64 roduct-state":{"fmod
2021-10-20 00:07:00.882 Dyson Pure: (Dyson Pure) 22 3a 5b 22 41 55 54 4f 22 2c 22 41 55 54 4f 22 5d 2c 22 66 ":["AUTO","AUTO"],"f
2021-10-20 00:07:00.882 Dyson Pure: (Dyson Pure) 6e 73 74 22 3a 5b 22 4f 46 46 22 2c 22 4f 46 46 22 5d 2c 22 nst":["OFF","OFF"],"
2021-10-20 00:07:00.883 Dyson Pure: (Dyson Pure) 66 6e 73 70 22 3a 5b 22 41 55 54 4f 22 2c 22 41 55 54 4f 22 fnsp":["AUTO","AUTO"
2021-10-20 00:07:00.883 Dyson Pure: (Dyson Pure) 5d 2c 22 71 74 61 72 22 3a 5b 22 30 30 30 33 22 2c 22 30 30 ],"qtar":["0003","00
2021-10-20 00:07:00.884 Dyson Pure: (Dyson Pure) 30 33 22 5d 2c 22 6f 73 6f 6e 22 3a 5b 22 4f 46 46 22 2c 22 03"],"oson":["OFF","
2021-10-20 00:07:00.884 Dyson Pure: (Dyson Pure) 4f 46 46 22 5d 2c 22 72 68 74 6d 22 3a 5b 22 4f 4e 22 2c 22 OFF"],"rhtm":["ON","
2021-10-20 00:07:00.885 Dyson Pure: (Dyson Pure) 4f 4e 22 5d 2c 22 66 69 6c 66 22 3a 5b 22 34 31 32 38 22 2c ON"],"filf":["4128",
2021-10-20 00:07:00.885 Dyson Pure: (Dyson Pure) 22 34 31 32 38 22 5d 2c 22 65 72 63 64 22 3a 5b 22 4e 4f 4e "4128"],"ercd":["NON
2021-10-20 00:07:00.886 Dyson Pure: (Dyson Pure) 45 22 2c 22 4e 4f 4e 45 22 5d 2c 22 6e 6d 6f 64 22 3a 5b 22 E","NONE"],"nmod":["
2021-10-20 00:07:00.886 Dyson Pure: (Dyson Pure) 4f 46 46 22 2c 22 4f 46 46 22 5d 2c 22 77 61 63 64 22 3a 5b OFF","OFF"],"wacd":[
2021-10-20 00:07:00.887 Dyson Pure: (Dyson Pure) 22 4e 4f 4e 45 22 2c 22 4e 4f 4e 45 22 5d 2c 22 68 6d 6f 64 "NONE","NONE"],"hmod
2021-10-20 00:07:00.887 Dyson Pure: (Dyson Pure) 22 3a 5b 22 4f 46 46 22 2c 22 4f 46 46 22 5d 2c 22 68 6d 61 ":["OFF","OFF"],"hma
2021-10-20 00:07:00.887 Dyson Pure: (Dyson Pure) 78 22 3a 5b 22 32 39 34 30 22 2c 22 32 39 34 30 22 5d 2c 22 x":["2940","2940"],"
2021-10-20 00:07:00.887 Dyson Pure: (Dyson Pure) 68 73 74 61 22 3a 5b 22 4f 46 46 22 2c 22 4f 46 46 22 5d 2c hsta":["OFF","OFF"],
2021-10-20 00:07:00.887 Dyson Pure: (Dyson Pure) 22 66 66 6f 63 22 3a 5b 22 4f 4e 22 2c 22 4f 4e 22 5d 2c 22 "ffoc":["ON","ON"],"
2021-10-20 00:07:00.887 Dyson Pure: (Dyson Pure) 74 69 6c 74 22 3a 5b 22 4f 4b 22 2c 22 4f 4b 22 5d 7d 2c 22 tilt":["OK","OK"]},"
2021-10-20 00:07:00.887 Dyson Pure: (Dyson Pure) 73 63 68 65 64 75 6c 65 72 22 3a 7b 22 73 72 73 63 22 3a 22 scheduler":{"srsc":"
2021-10-20 00:07:00.887 Dyson Pure: (Dyson Pure) 64 65 35 65 22 2c 22 64 73 74 76 22 3a 22 30 30 30 31 22 2c de5e","dstv":"0001",
2021-10-20 00:07:00.887 Dyson Pure: (Dyson Pure) 22 74 7a 69 64 22 3a 22 30 30 30 31 22 7d 7d .. .. .. .. .. "tzid":"0001"}}
2021-10-20 00:07:00.888 Dyson Pure: (Dyson Pure) MqttClient::onMessage Topic '455/PT4-EU-NEA5093A/status/current', Data[Verb]: 'PUBLISH'
2021-10-20 00:07:00.888 Dyson Pure: (Dyson Pure) MQTT Publish: MQTT message incoming: 455/PT4-EU-NEA5093A/status/current {'msg': 'STATE-CHANGE', 'time': '2021-10-19T22:07:01.000Z', 'mode-reason': 'LAPP', 'state-reason': 'MODE', 'product-state': {'fmod': ['AUTO', 'AUTO'], 'fnst': ['OFF', 'OFF'], 'fnsp': ['AUTO', 'AUTO'], 'qtar': ['0003', '0003'], 'oson': ['OFF', 'OFF'], 'rhtm': ['ON', 'ON'], 'filf': ['4128', '4128'], 'ercd': ['NONE', 'NONE'], 'nmod': ['OFF', 'OFF'], 'wacd': ['NONE', 'NONE'], 'hmod': ['OFF', 'OFF'], 'hmax': ['2940', '2940'], 'hsta': ['OFF', 'OFF'], 'ffoc': ['ON', 'ON'], 'tilt': ['OK', 'OK']}, 'scheduler': {'srsc': 'de5e', 'dstv': '0001', 'tzid': '0001'}}
2021-10-20 00:07:00.889 Dyson Pure: (Dyson Pure) machine state or state change recieved
2021-10-20 00:07:00.889 Dyson Pure: (Dyson Pure) update fanspeed, state of FanMode: AUTO
2021-10-20 00:07:00.889 Dyson Pure: (Dyson Pure) update StateData: StateData: Fan mode: AUTO + state: OFF, speed: AUTO, AirQual target: MEDIUM night mode: OFF, Oscillation: OFF, Filter life: 4128, Standby monitoring: ON, error: Error code: NONE, warning: No warning
2021-10-20 00:07:00.392 Status: dzVents: Info: template: ------ Start internal script: Script #2:, trigger: "every minute"
2021-10-20 00:07:00.415 Status: dzVents: Info: template: ------ Finished Script #2
2021-10-20 00:07:00.417 Status: EventSystem: Script event triggered: /opt/yunohost/domoticz/dzVents/runtime/dzVents.lua
2021-10-20 00:07:05.098 Dyson Pure: (Dyson Pure) Polling unit in 2 heartbeats.
2021-10-20 00:07:05.099 Dyson Pure: (Dyson Pure) Sending 2 bytes of data
````
Here are the logs when trying to switch on via the script with `heatmode.switchSelector('Heating')` ( not working):
````
 2021-10-20 00:29:00.750 Dyson Pure: (Dyson Pure) DysonPureLink plugin: onCommand called for Unit 18: Parameter 'Set Level', Level: 10
2021-10-20 00:29:00.750 Dyson Pure: (Dyson Pure) MqttClient::Publish 455/PT4-EU-NEA5093A/command ({"msg": "STATE-SET", "mode-reason": "LAPP", "data": {"hmod": "OFF"}, "time": "2021-10-19T22:29:00Z"})
2021-10-20 00:29:00.751 Dyson Pure: (Dyson Pure) Sending 132 bytes of data
2021-10-20 00:29:00.751 Dyson Pure: (Dyson Pure) 30 81 01 00 1b 34 35 35 2f 50 54 34 2d 45 55 2d 4e 45 41 35 0�..455/PT4-EU-NEA5
2021-10-20 00:29:00.751 Dyson Pure: (Dyson Pure) 30 39 33 41 2f 63 6f 6d 6d 61 6e 64 7b 22 6d 73 67 22 3a 20 093A/command{"msg":.
2021-10-20 00:29:00.751 Dyson Pure: (Dyson Pure) 22 53 54 41 54 45 2d 53 45 54 22 2c 20 22 6d 6f 64 65 2d 72 "STATE-SET",."mode-r
2021-10-20 00:29:00.751 Dyson Pure: (Dyson Pure) 65 61 73 6f 6e 22 3a 20 22 4c 41 50 50 22 2c 20 22 64 61 74 eason":."LAPP",."dat
2021-10-20 00:29:00.751 Dyson Pure: (Dyson Pure) 61 22 3a 20 7b 22 68 6d 6f 64 22 3a 20 22 4f 46 46 22 7d 2c a":.{"hmod":."OFF"},
2021-10-20 00:29:00.751 Dyson Pure: (Dyson Pure) 20 22 74 69 6d 65 22 3a 20 22 32 30 32 31 2d 31 30 2d 31 39 ."time":."2021-10-19
2021-10-20 00:29:00.751 Dyson Pure: (Dyson Pure) 54 32 32 3a 32 39 3a 30 30 5a 22 7d .. .. .. .. .. .. .. .. T22:29:00Z"}
2021-10-20 00:29:00.692 Status: dzVents: Info: template: ------ Start internal script: Script #2:, trigger: "every minute"
2021-10-20 00:29:00.716 Status: dzVents: Info: template: ------ Finished Script #2
2021-10-20 00:29:00.718 Status: EventSystem: Script event triggered: /opt/yunohost/domoticz/dzVents/runtime/dzVents.lua
2021-10-20 00:29:01.202 Dyson Pure: (Dyson Pure) Received 535 bytes of data
2021-10-20 00:29:01.203 Dyson Pure: (Dyson Pure) 30 94 04 00 22 34 35 35 2f 50 54 34 2d 45 55 2d 4e 45 41 35 0Ԯ."455/PT4-EU-NEA5
2021-10-20 00:29:01.203 Dyson Pure: (Dyson Pure) 30 39 33 41 2f 73 74 61 74 75 73 2f 63 75 72 72 65 6e 74 7b 093A/status/current{
2021-10-20 00:29:01.204 Dyson Pure: (Dyson Pure) 22 6d 73 67 22 3a 22 53 54 41 54 45 2d 43 48 41 4e 47 45 22 "msg":"STATE-CHANGE"
2021-10-20 00:29:01.204 Dyson Pure: (Dyson Pure) 2c 22 74 69 6d 65 22 3a 22 32 30 32 31 2d 31 30 2d 31 39 54 ,"time":"2021-10-19T
2021-10-20 00:29:01.205 Dyson Pure: (Dyson Pure) 32 32 3a 32 39 3a 30 31 2e 30 30 30 5a 22 2c 22 6d 6f 64 65 22:29:01.000Z","mode
2021-10-20 00:29:01.205 Dyson Pure: (Dyson Pure) 2d 72 65 61 73 6f 6e 22 3a 22 4c 41 50 50 22 2c 22 73 74 61 -reason":"LAPP","sta
2021-10-20 00:29:01.205 Dyson Pure: (Dyson Pure) 74 65 2d 72 65 61 73 6f 6e 22 3a 22 4d 4f 44 45 22 2c 22 70 te-reason":"MODE","p
2021-10-20 00:29:01.206 Dyson Pure: (Dyson Pure) 72 6f 64 75 63 74 2d 73 74 61 74 65 22 3a 7b 22 66 6d 6f 64 roduct-state":{"fmod
2021-10-20 00:29:01.206 Dyson Pure: (Dyson Pure) 22 3a 5b 22 41 55 54 4f 22 2c 22 41 55 54 4f 22 5d 2c 22 66 ":["AUTO","AUTO"],"f
2021-10-20 00:29:01.207 Dyson Pure: (Dyson Pure) 6e 73 74 22 3a 5b 22 4f 46 46 22 2c 22 4f 46 46 22 5d 2c 22 nst":["OFF","OFF"],"
2021-10-20 00:29:01.207 Dyson Pure: (Dyson Pure) 66 6e 73 70 22 3a 5b 22 41 55 54 4f 22 2c 22 41 55 54 4f 22 fnsp":["AUTO","AUTO"
2021-10-20 00:29:01.208 Dyson Pure: (Dyson Pure) 5d 2c 22 71 74 61 72 22 3a 5b 22 30 30 30 33 22 2c 22 30 30 ],"qtar":["0003","00
2021-10-20 00:29:01.208 Dyson Pure: (Dyson Pure) 30 33 22 5d 2c 22 6f 73 6f 6e 22 3a 5b 22 4f 46 46 22 2c 22 03"],"oson":["OFF","
2021-10-20 00:29:01.208 Dyson Pure: (Dyson Pure) 4f 46 46 22 5d 2c 22 72 68 74 6d 22 3a 5b 22 4f 4e 22 2c 22 OFF"],"rhtm":["ON","
2021-10-20 00:29:01.209 Dyson Pure: (Dyson Pure) 4f 4e 22 5d 2c 22 66 69 6c 66 22 3a 5b 22 34 31 32 38 22 2c ON"],"filf":["4128",
2021-10-20 00:29:01.209 Dyson Pure: (Dyson Pure) 22 34 31 32 38 22 5d 2c 22 65 72 63 64 22 3a 5b 22 4e 4f 4e "4128"],"ercd":["NON
2021-10-20 00:29:01.210 Dyson Pure: (Dyson Pure) 45 22 2c 22 4e 4f 4e 45 22 5d 2c 22 6e 6d 6f 64 22 3a 5b 22 E","NONE"],"nmod":["
2021-10-20 00:29:01.210 Dyson Pure: (Dyson Pure) 4f 46 46 22 2c 22 4f 46 46 22 5d 2c 22 77 61 63 64 22 3a 5b OFF","OFF"],"wacd":[
2021-10-20 00:29:01.211 Dyson Pure: (Dyson Pure) 22 4e 4f 4e 45 22 2c 22 4e 4f 4e 45 22 5d 2c 22 68 6d 6f 64 "NONE","NONE"],"hmod
2021-10-20 00:29:01.211 Dyson Pure: (Dyson Pure) 22 3a 5b 22 4f 46 46 22 2c 22 4f 46 46 22 5d 2c 22 68 6d 61 ":["OFF","OFF"],"hma
2021-10-20 00:29:01.212 Dyson Pure: (Dyson Pure) 78 22 3a 5b 22 32 39 34 30 22 2c 22 32 39 34 30 22 5d 2c 22 x":["2940","2940"],"
2021-10-20 00:29:01.212 Dyson Pure: (Dyson Pure) 68 73 74 61 22 3a 5b 22 4f 46 46 22 2c 22 4f 46 46 22 5d 2c hsta":["OFF","OFF"],
2021-10-20 00:29:01.212 Dyson Pure: (Dyson Pure) 22 66 66 6f 63 22 3a 5b 22 4f 4e 22 2c 22 4f 4e 22 5d 2c 22 "ffoc":["ON","ON"],"
2021-10-20 00:29:01.213 Dyson Pure: (Dyson Pure) 74 69 6c 74 22 3a 5b 22 4f 4b 22 2c 22 4f 4b 22 5d 7d 2c 22 tilt":["OK","OK"]},"
2021-10-20 00:29:01.213 Dyson Pure: (Dyson Pure) 73 63 68 65 64 75 6c 65 72 22 3a 7b 22 73 72 73 63 22 3a 22 scheduler":{"srsc":"
2021-10-20 00:29:01.214 Dyson Pure: (Dyson Pure) 64 65 35 65 22 2c 22 64 73 74 76 22 3a 22 30 30 30 31 22 2c de5e","dstv":"0001",
2021-10-20 00:29:01.214 Dyson Pure: (Dyson Pure) 22 74 7a 69 64 22 3a 22 30 30 30 31 22 7d 7d .. .. .. .. .. "tzid":"0001"}}
2021-10-20 00:29:01.215 Dyson Pure: (Dyson Pure) MqttClient::onMessage Topic '455/PT4-EU-NEA5093A/status/current', Data[Verb]: 'PUBLISH'
2021-10-20 00:29:01.216 Dyson Pure: (Dyson Pure) MQTT Publish: MQTT message incoming: 455/PT4-EU-NEA5093A/status/current {'msg': 'STATE-CHANGE', 'time': '2021-10-19T22:29:01.000Z', 'mode-reason': 'LAPP', 'state-reason': 'MODE', 'product-state': {'fmod': ['AUTO', 'AUTO'], 'fnst': ['OFF', 'OFF'], 'fnsp': ['AUTO', 'AUTO'], 'qtar': ['0003', '0003'], 'oson': ['OFF', 'OFF'], 'rhtm': ['ON', 'ON'], 'filf': ['4128', '4128'], 'ercd': ['NONE', 'NONE'], 'nmod': ['OFF', 'OFF'], 'wacd': ['NONE', 'NONE'], 'hmod': ['OFF', 'OFF'], 'hmax': ['2940', '2940'], 'hsta': ['OFF', 'OFF'], 'ffoc': ['ON', 'ON'], 'tilt': ['OK', 'OK']}, 'scheduler': {'srsc': 'de5e', 'dstv': '0001', 'tzid': '0001'}}
2021-10-20 00:29:01.216 Dyson Pure: (Dyson Pure) machine state or state change recieved
2021-10-20 00:29:01.217 Dyson Pure: (Dyson Pure) update fanspeed, state of FanMode: AUTO
2021-10-20 00:29:01.218 Dyson Pure: (Dyson Pure) update StateData: StateData: Fan mode: AUTO + state: OFF, speed: AUTO, AirQual target: MEDIUM night mode: OFF, Oscillation: OFF, Filter life: 4128, Standby monitoring: ON, error: Error code: NONE, warning: No warning 
````

Here is the log when I switch on the device via the control panel:
````
 2021-10-20 00:08:37.048 Dyson Pure: (Dyson Pure) DysonPureLink plugin: onCommand called for Unit 18: Parameter 'Set Level', Level: 20
2021-10-20 00:08:37.049 Dyson Pure: (Dyson Pure) MqttClient::Publish 455/PT4-EU-NEA5093A/command ({"msg": "STATE-SET", "mode-reason": "LAPP", "data": {"hmod": "HEAT"}, "time": "2021-10-19T22:08:37Z"})
2021-10-20 00:08:37.049 Dyson Pure: (Dyson Pure) Sending 133 bytes of data
2021-10-20 00:08:37.050 Dyson Pure: (Dyson Pure) 30 82 01 00 1b 34 35 35 2f 50 54 34 2d 45 55 2d 4e 45 41 35 0®..455/PT4-EU-NEA5
2021-10-20 00:08:37.050 Dyson Pure: (Dyson Pure) 30 39 33 41 2f 63 6f 6d 6d 61 6e 64 7b 22 6d 73 67 22 3a 20 093A/command{"msg":.
2021-10-20 00:08:37.050 Dyson Pure: (Dyson Pure) 22 53 54 41 54 45 2d 53 45 54 22 2c 20 22 6d 6f 64 65 2d 72 "STATE-SET",."mode-r
2021-10-20 00:08:37.050 Dyson Pure: (Dyson Pure) 65 61 73 6f 6e 22 3a 20 22 4c 41 50 50 22 2c 20 22 64 61 74 eason":."LAPP",."dat
2021-10-20 00:08:37.050 Dyson Pure: (Dyson Pure) 61 22 3a 20 7b 22 68 6d 6f 64 22 3a 20 22 48 45 41 54 22 7d a":.{"hmod":."HEAT"}
2021-10-20 00:08:37.050 Dyson Pure: (Dyson Pure) 2c 20 22 74 69 6d 65 22 3a 20 22 32 30 32 31 2d 31 30 2d 31 ,."time":."2021-10-1
2021-10-20 00:08:37.050 Dyson Pure: (Dyson Pure) 39 54 32 32 3a 30 38 3a 33 37 5a 22 7d .. .. .. .. .. .. .. 9T22:08:37Z"}
2021-10-20 00:08:37.502 Dyson Pure: (Dyson Pure) Received 536 bytes of data
2021-10-20 00:08:37.503 Dyson Pure: (Dyson Pure) 30 95 04 00 22 34 35 35 2f 50 54 34 2d 45 55 2d 4e 45 41 35 0ծ."455/PT4-EU-NEA5
2021-10-20 00:08:37.504 Dyson Pure: (Dyson Pure) 30 39 33 41 2f 73 74 61 74 75 73 2f 63 75 72 72 65 6e 74 7b 093A/status/current{
2021-10-20 00:08:37.505 Dyson Pure: (Dyson Pure) 22 6d 73 67 22 3a 22 53 54 41 54 45 2d 43 48 41 4e 47 45 22 "msg":"STATE-CHANGE"
2021-10-20 00:08:37.506 Dyson Pure: (Dyson Pure) 2c 22 74 69 6d 65 22 3a 22 32 30 32 31 2d 31 30 2d 31 39 54 ,"time":"2021-10-19T
2021-10-20 00:08:37.507 Dyson Pure: (Dyson Pure) 32 32 3a 30 38 3a 33 37 2e 30 30 30 5a 22 2c 22 6d 6f 64 65 22:08:37.000Z","mode
2021-10-20 00:08:37.508 Dyson Pure: (Dyson Pure) 2d 72 65 61 73 6f 6e 22 3a 22 4c 41 50 50 22 2c 22 73 74 61 -reason":"LAPP","sta
2021-10-20 00:08:37.509 Dyson Pure: (Dyson Pure) 74 65 2d 72 65 61 73 6f 6e 22 3a 22 4d 4f 44 45 22 2c 22 70 te-reason":"MODE","p
2021-10-20 00:08:37.510 Dyson Pure: (Dyson Pure) 72 6f 64 75 63 74 2d 73 74 61 74 65 22 3a 7b 22 66 6d 6f 64 roduct-state":{"fmod
2021-10-20 00:08:37.511 Dyson Pure: (Dyson Pure) 22 3a 5b 22 41 55 54 4f 22 2c 22 41 55 54 4f 22 5d 2c 22 66 ":["AUTO","AUTO"],"f
2021-10-20 00:08:37.512 Dyson Pure: (Dyson Pure) 6e 73 74 22 3a 5b 22 4f 46 46 22 2c 22 4f 46 46 22 5d 2c 22 nst":["OFF","OFF"],"
2021-10-20 00:08:37.513 Dyson Pure: (Dyson Pure) 66 6e 73 70 22 3a 5b 22 41 55 54 4f 22 2c 22 41 55 54 4f 22 fnsp":["AUTO","AUTO"
2021-10-20 00:08:37.514 Dyson Pure: (Dyson Pure) 5d 2c 22 71 74 61 72 22 3a 5b 22 30 30 30 33 22 2c 22 30 30 ],"qtar":["0003","00
2021-10-20 00:08:37.515 Dyson Pure: (Dyson Pure) 30 33 22 5d 2c 22 6f 73 6f 6e 22 3a 5b 22 4f 46 46 22 2c 22 03"],"oson":["OFF","
2021-10-20 00:08:37.516 Dyson Pure: (Dyson Pure) 4f 46 46 22 5d 2c 22 72 68 74 6d 22 3a 5b 22 4f 4e 22 2c 22 OFF"],"rhtm":["ON","
2021-10-20 00:08:37.516 Dyson Pure: (Dyson Pure) 4f 4e 22 5d 2c 22 66 69 6c 66 22 3a 5b 22 34 31 32 38 22 2c ON"],"filf":["4128",
2021-10-20 00:08:37.516 Dyson Pure: (Dyson Pure) 22 34 31 32 38 22 5d 2c 22 65 72 63 64 22 3a 5b 22 4e 4f 4e "4128"],"ercd":["NON
2021-10-20 00:08:37.516 Dyson Pure: (Dyson Pure) 45 22 2c 22 4e 4f 4e 45 22 5d 2c 22 6e 6d 6f 64 22 3a 5b 22 E","NONE"],"nmod":["
2021-10-20 00:08:37.516 Dyson Pure: (Dyson Pure) 4f 46 46 22 2c 22 4f 46 46 22 5d 2c 22 77 61 63 64 22 3a 5b OFF","OFF"],"wacd":[
2021-10-20 00:08:37.516 Dyson Pure: (Dyson Pure) 22 4e 4f 4e 45 22 2c 22 4e 4f 4e 45 22 5d 2c 22 68 6d 6f 64 "NONE","NONE"],"hmod
2021-10-20 00:08:37.516 Dyson Pure: (Dyson Pure) 22 3a 5b 22 4f 46 46 22 2c 22 48 45 41 54 22 5d 2c 22 68 6d ":["OFF","HEAT"],"hm
2021-10-20 00:08:37.517 Dyson Pure: (Dyson Pure) 61 78 22 3a 5b 22 32 39 34 30 22 2c 22 32 39 34 30 22 5d 2c ax":["2940","2940"],
2021-10-20 00:08:37.517 Dyson Pure: (Dyson Pure) 22 68 73 74 61 22 3a 5b 22 4f 46 46 22 2c 22 4f 46 46 22 5d "hsta":["OFF","OFF"]
2021-10-20 00:08:37.517 Dyson Pure: (Dyson Pure) 2c 22 66 66 6f 63 22 3a 5b 22 4f 4e 22 2c 22 4f 4e 22 5d 2c ,"ffoc":["ON","ON"],
2021-10-20 00:08:37.517 Dyson Pure: (Dyson Pure) 22 74 69 6c 74 22 3a 5b 22 4f 4b 22 2c 22 4f 4b 22 5d 7d 2c "tilt":["OK","OK"]},
2021-10-20 00:08:37.517 Dyson Pure: (Dyson Pure) 22 73 63 68 65 64 75 6c 65 72 22 3a 7b 22 73 72 73 63 22 3a "scheduler":{"srsc":
2021-10-20 00:08:37.517 Dyson Pure: (Dyson Pure) 22 64 65 35 65 22 2c 22 64 73 74 76 22 3a 22 30 30 30 31 22 "de5e","dstv":"0001"
2021-10-20 00:08:37.517 Dyson Pure: (Dyson Pure) 2c 22 74 7a 69 64 22 3a 22 30 30 30 31 22 7d 7d .. .. .. .. ,"tzid":"0001"}}
2021-10-20 00:08:37.518 Dyson Pure: (Dyson Pure) MqttClient::onMessage Topic '455/PT4-EU-NEA5093A/status/current', Data[Verb]: 'PUBLISH'
2021-10-20 00:08:37.519 Dyson Pure: (Dyson Pure) MQTT Publish: MQTT message incoming: 455/PT4-EU-NEA5093A/status/current {'msg': 'STATE-CHANGE', 'time': '2021-10-19T22:08:37.000Z', 'mode-reason': 'LAPP', 'state-reason': 'MODE', 'product-state': {'fmod': ['AUTO', 'AUTO'], 'fnst': ['OFF', 'OFF'], 'fnsp': ['AUTO', 'AUTO'], 'qtar': ['0003', '0003'], 'oson': ['OFF', 'OFF'], 'rhtm': ['ON', 'ON'], 'filf': ['4128', '4128'], 'ercd': ['NONE', 'NONE'], 'nmod': ['OFF', 'OFF'], 'wacd': ['NONE', 'NONE'], 'hmod': ['OFF', 'HEAT'], 'hmax': ['2940', '2940'], 'hsta': ['OFF', 'OFF'], 'ffoc': ['ON', 'ON'], 'tilt': ['OK', 'OK']}, 'scheduler': {'srsc': 'de5e', 'dstv': '0001', 'tzid': '0001'}}
2021-10-20 00:08:37.519 Dyson Pure: (Dyson Pure) machine state or state change recieved
2021-10-20 00:08:37.519 Dyson Pure: (Dyson Pure) update fanspeed, state of FanMode: AUTO
2021-10-20 00:08:37.521 (Dyson Pure - Heat mode) Updating device from 0:'10' to have values 1:'20'.
2021-10-20 00:08:37.563 Dyson Pure: (Dyson Pure) Update Dyson Pure - Heat mode: nValue 1 - sValue 20 - BatteryLevel 255
2021-10-20 00:08:37.564 Dyson Pure: (Dyson Pure) update StateData: StateData: Fan mode: AUTO + state: OFF, speed: AUTO, AirQual target: MEDIUM night mode: OFF, Oscillation: OFF, Filter life: 4128, Standby monitoring: ON, error: Error code: NONE, warning: No warning
2021-10-20 00:08:37.005 Status: User: Admin (IP: 127.0.0.1) initiated a switch command (57/Dyson Pure - Heat mode/Set Level)
````

What I notice is that, whichever value I set in the Dzvents script, the first line of the debug log will always say : `Set Level', Level: 10` and so will switch the device off.
I don't know exactly if the bug is from the plugin or from the domoticz Dzvent script, so apologies if this is not the right place to log the issue.

**Comment by Jan-nl** [comment] 2021-10-21 11:02
hm, I don't use dzVents but plain lua. I just checked and noticed I only switch the Dyson off through lua, switching on is mostly done through the Dyson app. 

I will do some checks with lua in the near future.

In the mean time, I know there are some more switches for operating the Dyson, can you try with on of them?

**Comment by Krakinou** [comment] 2021-10-21 20:21
Hello,
I tried a few of them : Fan mode, fan speed, oscillation mode, night mode, all of them seems to work, but I did not succeed to switch the dyson heating on whatever I tried.
I also successfully changed the heat target (even if there is a 1°C difference between my control panel and the set temperature, which is strange but is another subject).
Fan state and heating state seems to be read-only, as they merely indicate if the dyson is currently heating or the fan is currently running.

**Comment by Krakinou** [comment] 2021-10-21 20:38
I also tried lua script (never used those before, so I had to search a bit how it works:
This is working:
````
commandArray = {}

print ("Time based event fired");
-- loop through all the devices
for deviceName,deviceValue in pairs(otherdevices) do
    if (deviceName=='Dyson Pure - Heat mode') then
        if deviceValue == "Off" then
             commandArray[deviceName]='Set Level: 30'
        end
    end
end

return commandArray
````
while the exact Dzvent counterpart is not working:
````
	execute = function(domoticz, timer)
	    local heatmode = domoticz.devices('Dyson Pure - Heat mode')

		--This do nothing
		heatmode.switchSelector(30)
````

**Comment by Jan-nl** [comment] 2021-10-29 07:06
Owkee, I really don't know Dzvents, it is built in lua, so a lot should be similar.

What notice in you lua example, normally the set level is without the colon ':', but in case it works it works ;-)

So it looks like the problem is in Dzvents...

**Comment by JanJaapKo** [comment] 2021-12-09 20:50
Following @Jan-nl conclusion as being Dzvents issue (or the mode is read only...) so closing issue. When needed please propose a change for the plugin, since I do not have a fan with heatmode....

**Closed as completed by JanJaapKo** 2021-12-09 20:50 UTC
