### ISSUE TITLE
Dyson pure hot+cool link (455) issues

### ISSUE THREAD

**Issue by jferdelyi** [JanJaapKo/DysonPureLink#15] opened 2020-04-22 17:08 UTC
Hi, I have Dyson pure hot+cool link (455) and this is my feedback (master branch).

### **My configuration**
- Raspberry Pi 3 model B v1.2
- Raspbian GNU/Linux Buster (10) (up to date)
- Domoticz Version: 2020.1
- Homerbridge Version 0.4.53 

### **Switches**
- Fan mode **OK**
- Fan state **NOK** (but for me it's useless because "Fan mode" do the same thing with more options. It's can be used as "sensor" because, even it's impossible to switch ON/OFF the ventilator with it, if the status change, the value of this "switch" change as well)
- Night mode **NOK** 
- Fan speed **OK**
- Oscillation mode **OK**
- Standby monitor **NOK** (I'm not sure to understand what is it)

### **Sensors**
- Remaining filter life **OK**
- Air quality setpoint **NOK** (is still 0 and no data in the log)
- Temperature and Humidity **OK**
- Volatile organic **OK**
- Dust **OK**
- Sleep timer **OK**

### **Homebridge link**
I know it's not exactly the topic here but I think it's good to have some feedback about end-to-end integration. I use the Domoticz with Homebridge (HomeKit server) and nothing is working except:
- Oscillation mode
- Temperature and Humidity
- Volatile organic
- Dust

About "Fan mode" and "Fan speed", these switches are "Stateless Programmable Switch" in Homebridge. Apple Home App returns "This device needs a concentrator" and it's not working neither in Homebridge nor in Home App.

About "Remaining filter life" and "Sleep timer" these are not managed by Apple Home App. In Homebridge there is nothing about these two sensors (it's really strange).

**Comment by JanJaapKo** [comment] 2020-05-04 09:07
Hi @Djeef ,

Thanks for the feedback. When I create the devices in Domoticz, all of them are set to 'not used' because I can not be sure which device makes sense for which model (as I have only 1 type at home). So I choose to just 'dump' all info from the machine into a corresponding device in Domoticz. 

- I agree for instance fan state is not very useful, although there is the situation where 'fan mode' is auto and the machine decides it doesn't need to filter, then fan state will show 'off'. But I've got it set to unused.
- **Night mode**: Why do you set 'nigh mode' to NOK? Works fine with me? Perhaps not supported on your machine (can you see it in your app or on your remote?)
- **stand by monitor** is the state where the machine **always** monitors the air quality (meaning it will run at fan speed 1 even when you switch it off, can be annoying at night). I found indeed a bug that I forget to update this value. Should be fixed now (as read only, setting to be done via app).
- **Air quality target**: same as stand by monitor: forgot to update device value, should be fixed. Setting via the app. It is now just numeric, I will upgrade it to a nice level switch with enum later.
- **Homebridge** I'm not an Apple user, so no experience. But I think there the limitations come from Domoticz and not the plugin

Thanks a lot for the extensive testing. Please pull latest version and see it they work out for you as well

**Comment by hagen-p** [comment] 2020-10-11 10:47
ok finally got around to work on this :
 this is based on the version with heating support

- Fan state:  Shows the state of the fan...  works as intended - echo's the state of the fan mode ( as auto is on too) user can 
   simply not include it  in the list of active devices ✅
- Night Mode:  Correctly dims  the lights   when on and back bright when off. ✅
- Standby monitor:  if switched on, and then turning the fan mode off... the Dyson constantly cycles air to measure  
   temp/air quality as intended.  It does not do this when switched  standby monitor is set to off ✅  
   (You can control this even when fan mode is off. (like switching it off during the night to reduce noice level))
-  Air quality setpoint:  Domoticz and the app stay in sync, ✅  As a side note you need to be in auto mode for this to work, 
    add a note to the docs?

I  dont use home bridge either.. so can test that, but from a pure plugin perspective these items do as intended now and the issue can be closed

**Comment by JanJaapKo** [comment] 2020-10-22 14:40
Solved with #24

**Closed as completed by JanJaapKo** 2020-10-22 14:40 UTC
Labels: awaiting feedback
